project:
  type: book
book:
  author: "Carlson Büth and Benjamin Black"
  date: last-modified
  chapters:
    - index.qmd
    - intro.qmd
    - structure.qmd
    - pipeline/pipeline.qmd
    - summary.qmd
    - references.qmd
  issue-url: https://github.com/ethzplus/evoland-plus-HPC/issues/new/choose
  repo-actions: [source, issue]
  repo-subdir: evoland-plus-hpc-guide
  authority: Planning of Landscape and Urban Systems – PLUS (ETH Zurich)
  language: en
  license: MIT License
bibliography: references.bib
callout-appearance: minimal

format:
  html:
    theme: 
      light: [cosmo, theme-light.scss]
      dark: [cosmo, theme-dark.scss]
    link-external-icon: true
    link-external-newwindow: true
  # pdf:
  #   documentclass: scrreprt

execute:
  freeze: auto

